# Generated by Django 3.2.6 on 2021-12-18 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order_php', models.TextField(default='<?php ', verbose_name='Содержимое файла order.php')),
                ('instruction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инструкция')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('iso', models.CharField(max_length=2, verbose_name='Код ISO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PresetParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tracker', models.SmallIntegerField(choices=[(0, '---------'), (1, 'Keitaro'), (2, 'Binom')], default=1, verbose_name='Трекер')),
                ('traffic_source', models.SmallIntegerField(choices=[(0, '---------'), (1, 'Facebook'), (2, 'MGID')], default=1, verbose_name='Источник трафика')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен ПП для API')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('aff_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_promo.affiliatenetwork', verbose_name='ПП')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_tasks', models.TextField(verbose_name='Текст пакетных заданий')),
                ('status', models.SmallIntegerField(choices=[(0, '---------'), (1, 'Новый'), (2, 'Выполняется...'), (3, 'Выполнен.'), (10, 'Ошибка в парсере!')], default=1, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_promo', models.CharField(max_length=255, verbose_name='Промо')),
                ('archive_promo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подготовленный промо-архив')),
                ('type_promo', models.SmallIntegerField(choices=[(1, 'Прокла'), (2, 'Ленд с оффером'), (3, 'Прокла с оффером')], verbose_name='Тип промо')),
                ('status', models.SmallIntegerField(choices=[(1, 'Парсится...'), (2, 'Готово'), (3, 'Загружен в Keitaro'), (10, 'Ошибка!'), (11, 'Ошибка загрузки в Keitaro!')], default=1, verbose_name='Статус')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Лог')),
                ('keitaro_type_promo', models.SmallIntegerField(blank=True, choices=[(1, 'Лендинг (keitaro)'), (2, 'Оффер (keitaro)')], null=True, verbose_name='Тип промо в Keitaro')),
                ('keitaro_promo_id', models.IntegerField(blank=True, null=True, verbose_name='ID лендинга/оффера в Keitaro')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parser_batch', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_promo.parserbatch', verbose_name='Пакетное задание')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_promo.presetparser', verbose_name='Пресет')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
