# Generated by Django 3.2.6 on 2021-12-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.TextField(verbose_name='Значение')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
