# Generated by Django 3.2.6 on 2021-12-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_promo', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedpromo',
            name='archive_promo_zip',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='parserbatch',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '---------'), (1, 'Новый'), (2, 'Выполняется'), (3, 'Выполнен.'), (10, 'Ошибка в парсере!')], default=1, verbose_name='Статус'),
        ),
    ]
