# Generated by Django 3.2.6 on 2021-12-21 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_promo', '0003_auto_20211221_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedpromo',
            name='geo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='downloadedpromo',
            name='keitaro_group_id',
            field=models.IntegerField(blank=True, default='0', verbose_name='Кейтаро id группы'),
            preserve_default=False,
        ),
    ]
